#启动hystrix
feign:
  hystrix:
    enabled: true

#hystrix全局配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000 #hystrix超时时间

#Ribbon全局配置
ribbon:
  ReadTimeout: 4000 #请求处理超时
  ConnectTimeout: 2000 #请求连接超时
  MaxAutoRetries: 0 #重试实例次数，不包括首次调用
  MaxAutoRetriesNextServer: 1 #切换其他实例次数，不包括首次所选

#Ribbon指定服务配置
test2-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡策略为：随机（默认是轮询，还有权重：WeightedResponseTimeRule）

spring:
  sleuth:
    sampler:
      percentage: 1 #采样比率(默认0.1=10%)
  #配置RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: '{cipher}AQCx+F442n8ixSyUkM7XAZEADrfd3QhICSKNBi1ee0z1HGSj1apWE2bLfqrgAOi3RN5Bxo3cj9xQYgacx7jpGfw4I920H8U+JtYl2mzGoe1j9jUFVw4+AXJrKCLxyuAiIgRF0UAZW6MN7Xobvg6Bbb2K4rWF9j3tlhNJPjVuJV7v/w5DVVtD95d+apgAFp+lGwyp2WwCo+PAySYecU4MO9+ZxthbjDwa9d+cpefzIggSqu1CTCGF2QKFUx7iKJiQYOS37jjIep8eiDRPF6pKqvz60o5H028pRAMuGD6/5WE2ETRicq3iybU7t/rYXMwv3mmuFWmv9gkhxUGWwqytmpcW/CkAqy7Oc32xI4x1OgSTfk2BDnVjzDbvtfEuJp1Anp8='